name: "${pluginName}"
version: ${pluginVersion}
description: ${pluginDescription}
api-version: "1.20"
main: net.deltapvp.template.libs.io.papermc.papertrail.RequiresPaperPlugins
author: ${pluginAuthor}